# Generated by Django 5.2.17 on 2026-09-15 18:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_alter_lead_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("whatsapp", "WhatsApp"),
                            ("site_visit", "Site Visit"),
                            ("sms", "SMS"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        default="outbound",
                        max_length=10,
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="crm.client",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("lead__isnull", False),
                            ("client__isnull", False),
                            _connector="OR",
                        ),
                        name="interaction_has_lead_or_client",
                    )
                ],
            },
        ),
    ]
