# Generated by Django 5.2.17 on 2026-09-25 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_restore_lost_reason_referred_by_agentquota"),
        ("properties", "0005_backfill_completion_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="property_interest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interested_leads",
                to="properties.property",
            ),
        ),
    ]
