# Generated by Django 5.2.17 on 2026-09-16 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("lead.assigned", "Lead assigned to you"),
                            ("viewing.completed", "Viewing outcome recorded"),
                            ("followup.due", "Follow-up due"),
                            ("followup.overdue", "Follow-up overdue"),
                            ("transaction.closed", "Transaction closed"),
                            ("transaction.commission_due", "Commission due for review"),
                            ("property.published", "Listing published"),
                            ("campaign.published", "Marketing campaign published"),
                            (
                                "property.pending_verification",
                                "Property submitted for verification",
                            ),
                            ("property.pending_approval", "Property awaiting approval"),
                        ],
                        max_length=64,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "event_type"),
                        name="unique_user_event_preference",
                    )
                ],
            },
        ),
    ]
