# Generated by Django 5.2.17 on 2026-10-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationpreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpreference",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("lead.assigned", "Lead assigned to you"),
                    ("viewing.completed", "Viewing outcome recorded"),
                    ("followup.due", "Follow-up due"),
                    ("followup.overdue", "Follow-up overdue"),
                    ("transaction.closed", "Transaction closed"),
                    ("transaction.commission_due", "Commission due for review"),
                    ("property.published", "Listing published"),
                    ("campaign.published", "Marketing campaign published"),
                    (
                        "property.pending_verification",
                        "Property submitted for verification",
                    ),
                ],
                max_length=64,
            ),
        ),
    ]
