# Generated by Django 5.2.17 on 2026-09-03 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("viewings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="viewing",
            options={"ordering": ["-created_at"]},
        ),
    ]
