# Generated by Django 5.2.17 on 2026-09-25 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_backfill_completion_percent"),
        ("public", "0002_contactsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactsubmission",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_submissions",
                to="properties.property",
            ),
        ),
    ]
