# Generated by Django 5.2.17 on 2026-09-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0003_contactsubmission_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactsubmission",
            name="bedrooms_preference",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
    ]
