# Generated by Django 5.2.17 on 2026-09-27 16:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_lead_property_interest"),
        ("properties", "0005_backfill_completion_percent"),
        ("public", "0004_contactsubmission_bedrooms_preference_and_more"),
        ("viewings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymousVisitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="savedproperty",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="propertyinquiry",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiries",
                to="public.customer",
            ),
        ),
        migrations.AlterField(
            model_name="savedproperty",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_properties",
                to="public.customer",
            ),
        ),
        migrations.AddField(
            model_name="propertyinquiry",
            name="visitor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiries",
                to="public.anonymousvisitor",
            ),
        ),
        migrations.AddField(
            model_name="savedproperty",
            name="visitor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_properties",
                to="public.anonymousvisitor",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyinquiry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("customer__isnull", False), ("visitor__isnull", True)),
                    models.Q(("customer__isnull", True), ("visitor__isnull", False)),
                    _connector="OR",
                ),
                name="inquiry_exactly_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="savedproperty",
            constraint=models.UniqueConstraint(
                condition=models.Q(("customer__isnull", False)),
                fields=("customer", "property"),
                name="unique_customer_saved_property",
            ),
        ),
        migrations.AddConstraint(
            model_name="savedproperty",
            constraint=models.UniqueConstraint(
                condition=models.Q(("visitor__isnull", False)),
                fields=("visitor", "property"),
                name="unique_visitor_saved_property",
            ),
        ),
        migrations.AddConstraint(
            model_name="savedproperty",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("customer__isnull", False), ("visitor__isnull", True)),
                    models.Q(("customer__isnull", True), ("visitor__isnull", False)),
                    _connector="OR",
                ),
                name="saved_property_exactly_one_owner",
            ),
        ),
    ]
