# Generated by Django 5.2.17 on 2026-10-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "public",
            "0005_anonymousvisitor_alter_savedproperty_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contactsubmission",
            name="requested_viewing_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="requested_viewing_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
