# Generated by Django 5.2.17 on 2026-09-01 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_department"),
        ("transactions", "0002_commissionrule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commissionrule",
            name="role",
            field=models.OneToOneField(
                blank=True,
                help_text="Leave blank for the default/fallback rule.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commission_rule",
                to="accounts.role",
            ),
        ),
    ]
