# Generated by Django 5.2.17 on 2026-09-03 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_alter_commissionrule_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-created_at"]},
        ),
    ]
