# Generated by Django 5.2.17 on 2026-09-16 00:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("paystack", "Paystack"),
                            ("cloudinary", "Cloudinary"),
                            ("email", "Email (SMTP)"),
                            ("sms", "SMS Gateway"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("configured", models.BooleanField(default=False)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_check_ok", models.BooleanField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="Horilux Estates", max_length=255)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="company/"),
                ),
                ("registered_address", models.TextField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                ("license_number", models.CharField(blank=True, max_length=100)),
                ("default_currency", models.CharField(default="GHS", max_length=8)),
                ("timezone", models.CharField(default="Africa/Accra", max_length=64)),
                (
                    "theme_primary_color",
                    models.CharField(default="#240270", max_length=9),
                ),
                (
                    "theme_secondary_color",
                    models.CharField(default="#003E03", max_length=9),
                ),
                (
                    "theme_accent_color",
                    models.CharField(default="#7A6D0C", max_length=9),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
