# Generated by Django 5.2.17 on 2026-08-27 01:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agent_split_percent",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.OneToOneField(
                        blank=True,
                        help_text="Leave blank for the default/fallback rule.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_rule",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("agent_split_percent__gte", 0),
                            ("agent_split_percent__lte", 100),
                        ),
                        name="commission_rule_split_between_0_and_100",
                    )
                ],
            },
        ),
    ]
