# Generated by Django 5.2.17 on 2026-08-30 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={"ordering": ["-created_at"]},
        ),
    ]
