# Generated by Django 5.2.17 on 2026-09-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_property_region_property_rental_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="inquiries_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
