# Generated by Django 5.2.17 on 2026-10-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_backfill_completion_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_verification", "Pending Verification"),
                    ("verified", "Verified"),
                    ("marketing_ready", "Marketing Ready"),
                    ("published", "Published"),
                    ("under_offer", "Under Offer"),
                    ("sold_rented", "Sold/Rented"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=25,
            ),
        ),
    ]
