"""
Board Pack PDF export.

Renders the same data returned by services.ceo_dashboard() -- the exact
function CEODashboardView uses for the on-screen dashboard -- as a formal
light-theme PDF report. Numbers in the PDF will always match the on-screen
dashboard since they come from the same cached function.
"""

import io
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, KeepTogether,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.lineplots import LinePlot
from reportlab.graphics.charts.barcharts import VerticalBarChart

BRAND_BLUE = colors.HexColor("#240270")
LIGHT_GREY = colors.HexColor("#f4f4f6")
TEXT_DARK = colors.HexColor("#1a1a2e")


def _format_ghs(value):
    return f"GHS {round(value):,}"


def _header_footer(canvas, doc):
    canvas.saveState()
    canvas.setFillColor(BRAND_BLUE)
    canvas.rect(0, A4[1] - 20 * mm, A4[0], 20 * mm, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 16)
    canvas.drawString(20 * mm, A4[1] - 13 * mm, "Horilux Estates — Board Pack")
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)
    canvas.drawString(20 * mm, 10 * mm, "Generated by Horilux CEO Dashboard")
    canvas.drawRightString(A4[0] - 20 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()


def generate_board_pack_pdf(data: dict) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=28 * mm, bottomMargin=18 * mm,
        leftMargin=20 * mm, rightMargin=20 * mm,
    )
    styles = getSampleStyleSheet()
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], textColor=BRAND_BLUE, spaceAfter=6)
    body = ParagraphStyle("body", parent=styles["Normal"], textColor=TEXT_DARK)

    elements = []

    # --- KPI summary table ---
    kpis = data.get("kpis", {})
    elements.append(Paragraph("Key Performance Indicators (YTD)", h2))
    kpi_rows = [
        ["Metric", "Value"],
        ["Gross Transaction Volume", _format_ghs(kpis.get("gross_volume_ytd", 0))],
        ["Average Deal Size", _format_ghs(kpis.get("avg_deal_size", 0))],
        ["Active Agents", str(kpis.get("active_agents", 0))],
        ["Active Mandates", str(kpis.get("active_mandates", 0))],
        ["Closed Yield", f"{kpis.get('closed_yield_percent', 0)}%"],
    ]
    kpi_table = Table(kpi_rows, colWidths=[100 * mm, 60 * mm])
    kpi_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_BLUE),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GREY]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dddddd")),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(kpi_table)
    elements.append(Spacer(1, 10 * mm))

    # --- Revenue trend line chart ---
    trend = data.get("revenue_trend", [])
    if trend:
        trend_block = [Paragraph("Revenue Trend", h2)]
        drawing = Drawing(170 * mm, 70 * mm)
        chart = LinePlot()
        chart.x = 10
        chart.y = 10
        chart.height = 55 * mm
        chart.width = 150 * mm
        current_series = [(i, row["current"]) for i, row in enumerate(trend)]
        prior_series = [(i, row["prior"]) for i, row in enumerate(trend)]
        chart.data = [current_series, prior_series]
        chart.lines[0].strokeColor = BRAND_BLUE
        chart.lines[0].strokeWidth = 2
        chart.lines[1].strokeColor = colors.HexColor("#aaaaaa")
        chart.lines[1].strokeWidth = 1
        chart.xValueAxis.valueMin = 0
        chart.xValueAxis.valueMax = max(len(trend) - 1, 1)
        chart.xValueAxis.labels.fontSize = 0
        chart.xValueAxis.visibleLabels = 0
        chart.yValueAxis.labelTextFormat = lambda v: _format_ghs(v)
        chart.yValueAxis.labels.fontSize = 7
        drawing.add(chart)
        trend_block.append(drawing)
        month_labels = "   ".join(row["month"] for row in trend)
        trend_block.append(Paragraph(f"<font size=7 color=grey>{month_labels}</font>", body))
        elements.append(KeepTogether(trend_block))
        elements.append(Spacer(1, 10 * mm))

    # --- Conversion funnel bar chart ---
    funnel = data.get("conversion_funnel", [])
    if funnel:
        funnel_block = [Paragraph("Deal Velocity Funnel", h2)]
        drawing = Drawing(170 * mm, 70 * mm)
        chart = VerticalBarChart()
        chart.x = 10
        chart.y = 10
        chart.height = 55 * mm
        chart.width = 150 * mm
        chart.data = [[stage["count"] for stage in funnel]]
        chart.categoryAxis.categoryNames = [stage["label"] for stage in funnel]
        chart.categoryAxis.labels.fontSize = 7
        chart.categoryAxis.labels.angle = 30
        chart.categoryAxis.labels.dy = -10
        chart.valueAxis.labels.fontSize = 7
        chart.bars[0].fillColor = BRAND_BLUE
        drawing.add(chart)
        funnel_block.append(drawing)
        elements.append(KeepTogether(funnel_block))
        elements.append(Spacer(1, 10 * mm))

    # --- Agent leaderboard table ---
    leaderboard = data.get("leaderboard", [])
    if leaderboard:
        elements.append(Paragraph("Top Agent Leaderboard", h2))
        lb_rows = [["Rank", "Agent", "Division", "Deals", "Volume", "Yield %"]]
        for row in leaderboard:
            lb_rows.append([
                str(row["rank"]),
                row["name"],
                row["division"],
                str(row["deals"]),
                _format_ghs(row["volume"]),
                f"{row['yield_percent']}%",
            ])
        lb_table = Table(lb_rows, colWidths=[15 * mm, 45 * mm, 35 * mm, 20 * mm, 30 * mm, 20 * mm])
        lb_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), BRAND_BLUE),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GREY]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dddddd")),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        elements.append(lb_table)

    doc.build(elements, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return buffer.getvalue()
