web: export DJANGO_SETTINGS_MODULE=Horilux.settings.production && python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn Horilux.wsgi:application --bind 0.0.0.0:$PORT --env DJANGO_SETTINGS_MODULE=Horilux.settings.production
release: DJANGO_SETTINGS_MODULE=Horilux.settings.production python manage.py migrate --noinput
